kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: go-comp
  labels:
    app: go-comp
    app.kubernetes.io/component: go-comp
    app.kubernetes.io/instance: go-comp
    app.kubernetes.io/name: golang
    app.kubernetes.io/part-of: go-app
    app.openshift.io/runtime: golang
    app.openshift.io/runtime-version: latest
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/stephanLandwehr/pubGitHub-ostests.git'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'go-comp:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'golang:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/stephanLandwehr/pubGitHub-ostests.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: go-comp-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: go-comp-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/golang@sha256:ebfed97ee40d3e38794a12c10587082173e90546d2cb97514d7e42457ec156b7
    - type: ConfigChange
  runPolicy: Serial