kind: Service
apiVersion: v1
metadata:
  name: go-comp-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
  selector:
    app: go-comp
  type: ClusterIP
  sessionAffinity: None